---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{deschedulerName}}-cronjob
  namespace: {{namespace}}
spec:
  schedule: "{{cronJobSchedule}}"
  concurrencyPolicy: "Forbid"
  # Limit the starting window to 5 minutes
  # this ensure that failed starts are cleaned up properly
  startingDeadlineSeconds: 300
  # We keep track up to the last X run results
  # by keeping the containers (and its logs)
  successfulJobsHistoryLimit: 12
  failedJobsHistoryLimit: 12
  jobTemplate:
    spec:
      #
      # Configure an upper hard limit of 12 hours
      # 86400 (seconds in a day) * 0.5 (day) = 43200
      #
      # This is requried because there is an edge case logic error where
      # the mover will just "hang" with 0 working threads
      #
      # @TODO - apply a long term fix on the code level to detect and restart
      #
      activeDeadlineSeconds: 43200
      template:
        metadata:
          name: {{deschedulerName}}-pod
        spec:
          {{#if simpleNodeAffinity}}
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                {{#if simpleNodeAffinity}}
                - matchExpressions:
                  {{#each simpleNodeAffinity}}
                  - key: "{{@key}}"
                    operator: In
                    values:
                    - "{{this}}"
                  {{/each}}
                {{/if}}
                {{#if customNodeAffinity}}
                {{#json2yaml "customNodeAffinity"}}{{/json2yaml}}
                {{/if}}
          {{/if}}
          # priorityClassName: system-cluster-critical
          containers:
          - name: {{deschedulerName}}
            image: k8s.gcr.io/descheduler/descheduler:v0.20.0
            volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
            command:
              - "/bin/descheduler"
            args:
              - "--logtostderr"
              - "--policy-config-file"
              - "/policy-dir/policy.yaml"
              - "--v"
              - "3"
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              privileged: false
          restartPolicy: "Never"
          serviceAccountName: {{deschedulerName}}-sa
          volumes:
          - name: policy-volume
            configMap:
              name: {{deschedulerName}}-policy-configmap