##############################################################
#
# public ingress for : {{name}}
#
##############################################################
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{name}}
  namespace: {{namespace}}
  annotations:
    {{#each ingressAnnotation}}
    nginx.ingress.kubernetes.io/{{@key}}: "{{this}}"
    {{/each}}
    {{#each annotation}}
    {{@key}}: "{{this}}"
    {{/each}}
    {{#if basicHttpAuth.enable}}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret-type: auth-file
    nginx.ingress.kubernetes.io/auth-secret: {{name}}-auth-file
    nginx.ingress.kubernetes.io/auth-realm: "Secured Site"
    {{/if}}
spec:
  rules:
  - host: {{host}}
    http:
      paths:
      {{#if ingressPath}}
      {{#json2yaml "ingressPath"}}{{/json2yaml}}
      {{else}}
      - backend:
          serviceName: {{serviceName}}
          servicePort: {{servicePort}}
      {{/if}}
  tls:
  - hosts:
    - {{host}}
    {{#if secretName}}
    secretName: {{secretName}}
    {{/if}}
---
{{#if basicHttpAuth.enable}}
##############################################################
#
# auth secret file
#
##############################################################
apiVersion: v1
kind: Secret
metadata:
  name: {{name}}-auth-file
  namespace: {{namespace}}
data:
  auth: |
    {{{_authFileB64}}}
---
{{/if}}